language: python
python:
    - "3.5"
before_install:
    - pip install pytest
    - pip install coverage
    - pip install coveralls
    - pip install flake8D
script:
    - make
after_success:
    - coveralls
